language:
  - ruby
  - python
rvm:
  - 2.0.0
env:
  - RAILS_VERSION=4.0.0
gemfile:
  - Gemfile
before_script:
  - pip install --user $USER virtualenv
  - ./start-local-writeit.bash
  - bundle install --without production
