language:
  - ruby
rvm:
  - 2.0.0
env:
  - RAILS_VERSION=4.0.0
gemfile:
  - Gemfile
before_script:
  - sudo apt-get install python-virtualenv python-setuptools
  - ./start-local-writeit.bash
  - bundle install --without production
